### Constructores de matrices

NumPy provee diversas funciones para crear matrices , algunas de las cuales ya vimos cuando estudiamos vectores , la diferencia consiste en que ahora ya no usamos un número para indicar el tamaño de un vector, si no una **tupla** de 2 elementos: (m,n) . Algunas de las funciones  que aplican tanto a vectores como a matrices son:

* np.array: crear una matriz a partir de una lista de listas: cada fila es una sublista
* np.zeros: crear una matriz de ceros
* np.ones: crear una matriz de unos
* np.empty: crear una matriz sin importarnos sus valores
* np.full: crear una matriz  con cierto valor
* np.copy: crea un clon o copia de cierta matriz

Algunas funciones específicas de matrices son:

* np.matrix: resultado casi idéntico a la función más general np.array, pero posee algunas propiedades adicionales específicas de listas, por ejemplo notación sencilla para inversas de matrices.
* np.eye: crear una matriz con 1s en su diagonal principal y ceros en el resto
* np.identity : crear una matriz identidad

Algunas funciones que solo aplican a vectores y no a matrices son:

* np.arange
* np.linspace

Existen otras pero estas son posiblemente las mas comunes. Puedes consultar las otras disponibles en: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
matriz_1 = np.matrix([[-1,2,3],
                      [-2,0,1],
                      [0,-1,-1]])

tamaño_matriz = matriz_1.shape

print("Rango del tensor:",matriz_1.ndim) #rango del tensor, para matriz es 2
print("Forma o tamaño:",tamaño_matriz) # tupla representando el tamaño de la matríz

print("Matriz de ceros de forma:",tamaño_matriz)
print("Filas:",tamaño_matriz[0])
print("Columnas:",tamaño_matriz[1])
print("Matriz:")
print(matriz_1)
print("Matriz Inversa:")
print(matriz_1.I)

Rango del tensor: 2
Forma o tamaño: (3, 3)
Matriz de ceros de forma: (3, 3)
Filas: 3
Columnas: 3
Matriz:
[[-1  2  3]
 [-2  0  1]
 [ 0 -1 -1]]
Matriz Inversa:
[[ 1. -1.  2.]
 [-2.  1. -5.]
 [ 2. -1.  4.]]


In [6]:
matriz_vacia = np.empty((2,3))

tamaño_matriz = matriz_vacia.shape

print("Rango del tensor:",matriz_vacia.ndim) #rango del tensor, para matriz es 2
print("Forma o tamaño:",tamaño_matriz) # tupla representando el tamaño de la matríz

print("Matriz de ceros de forma:",tamaño_matriz)
print("Filas:",tamaño_matriz[0])
print("Columnas:",tamaño_matriz[1])
print("Matriz:")
print(matriz_vacia)

Rango del tensor: 2
Forma o tamaño: (2, 3)
Matriz de ceros de forma: (2, 3)
Filas: 2
Columnas: 3
Matriz:
[[0.00000000e+000 8.51769173e-321 0.00000000e+000]
 [1.19461626e-311 0.00000000e+000 3.25060610e-319]]


In [7]:
matriz_ochos = np.full((4,5),8)

tamaño_matriz = matriz_ochos.shape

print("Rango del tensor:",matriz_ochos.ndim) #rango del tensor, para matriz es 2
print("Forma o tamaño:",tamaño_matriz) # tupla representando el tamaño de la matríz

print("Matriz de ceros de forma:",tamaño_matriz)
print("Filas:",tamaño_matriz[0])
print("Columnas:",tamaño_matriz[1])
print("Matriz:")
print(matriz_ochos)

Rango del tensor: 2
Forma o tamaño: (4, 5)
Matriz de ceros de forma: (4, 5)
Filas: 4
Columnas: 5
Matriz:
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


** DIFERENCIAS np.array y np.matrix**

<li>Los elementos de un np.array son multidimensionales y los objetos de una np.matrix son bidimensionales</li>
<li>Se comportan diferente con el operador **  porque en un array se convieren en valores cuadrados encambio en una matriz se multiplican los valores</li>
<li>La matriz es un subelemento de la clase array</li>
<li>Se usa mas a menudo la np.array</li>


Ref: https://towardsdatascience.com/6-key-differences-between-np-ndarray-and-np-matrix-objects-e3f5234ae327